### ISSUE TITLE
Problem of not being able to scroll when initialIndex parameter is passed

### ISSUE THREAD

**Issue by celikdemirrberkay** [shivbo96/page_flip#26]
Hello, we are using the package in our project. We are giving a total of nearly 6666 pages to the PageFlipWidget child. When we want to start from the relevant page (for example, page 46), we pass 46 to its initialIndex and the widget becomes highlighted as in the attachment and cannot scroll. How can we solve this?

<img width="264" alt="Screenshot 2024-11-27 at 15 19 32" src="https://github.com/user-attachments/assets/4975251e-f1f6-4caf-bf04-a673e0c6692c">

**Comment by shamird** [comment]
@celikdemirrberkay Did you find a solution? How did you fix it?

**Comment by celikdemirrberkay** [comment]
if you add the specific line on page_flip_widget.dart line 94 problem will be solved.

if (widget.initialIndex != 0) {
      currentPage = ValueNotifier(-1); /// ----> Add this line 
      currentWidget = ValueNotifier(pages[pageNumber]);
      currentPageIndex = ValueNotifier(widget.initialIndex);
    }
