### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by MohammadUzair1** [shivbo96/page_flip#3]
Performance is too low when pages increases like after 30 pages it fluctuates and app crashes

**Comment by shivbo96** [comment]
Hi @MohammadUzair1  we are working on the optimisation on the the flip will see an update soon

**Comment by shivbo96** [comment]
Hi @MohammadUzair1  The issue has been resolved please check latest version of the dependency ( page_flip: ^0.1.0 ). 
Thanks for showing the patience  cheers ✌🏼
