### ISSUE TITLE
initialIndex property is not working

### ISSUE THREAD

**Issue by volkankahraman** [shivbo96/page_flip#4]
**initialIndex** property is not working I think the reason is the code below instead of using pageNumber this condition assigns 0 

> page_flip_widget.dart
```dart
68    if (widget.children.isNotEmpty) {
69     currentChild.value = Center(child: widget.children[0]);
70    }
``` 
@shivbo96

**Comment by shivbo96** [comment]
@volkankahraman  The issue has been resolved please check latest version of the dependency ( page_flip: ^0.1.0 ). 
Thanks for showing the patience  cheers ✌🏼

**Comment by volkankahraman** [comment]
Thanks for the effort, great package.
