### ISSUE TITLE
lastPage issues trying to reset the controller. 

### ISSUE THREAD

**Issue by vnl** [shivbo96/page_flip#8]
Created a button on the last page to reset and go to Page 1. I used the following:

```
PageFlipWidget(
                  key: _controller,
                  lastPage: Center(
                    child: TextButton(
                      onPressed: () {
                        debugPrint("Read Again Pressed");
                        _controller.currentState?.goToPage(0);
                        setState(() {});
                      },
                      child: const Text(
                        'Read Again',
                      ),
                    ),
                  ),
                  children: <Widget>[
                    for (int i = 0; i < splitStory.length; i++)
                      StoryFlipBook(
                        story: splitStory[i],
                        pageNumber: i,
                        totalPages: splitStory.length,
                      )
                  ],
                ),
```

I have attached a few screenshots. The flip animation does not work, then flickers the last page and loads the final page. 

![image](https://github.com/shivbo96/page_flip/assets/1355466/2226dfbc-da2e-4a22-ab34-e5c09b95829c)
![image](https://github.com/shivbo96/page_flip/assets/1355466/5e88b1d9-4dab-4b07-a7b3-2385a0e56dfe)
![image](https://github.com/shivbo96/page_flip/assets/1355466/aadf7e58-36be-4cb2-aec4-48486df8892a)
![image](https://github.com/shivbo96/page_flip/assets/1355466/28953b5c-b31d-4c6c-ab68-39402907cd78)

This issue only occurs when I set this line: _controller.currentState?.goToPage(0);
In a way, I cannot go to the first page if I wanted to with that. 

Any suggestions?

**Comment by shivbo96** [comment]
Hi @vnl  I will look into it and get back to asap

**Comment by vnl** [comment]
Hey, @shivbo96, any chance you got time to check this out?

**Comment by vnl** [comment]
@shivbo96 I'm bumping this up a bit. :)

**Comment by shivbo96** [comment]
Hi @vnl  This issue is fixed now try to update the library  to latest version ( page_flip: ^0.2.1 )
